name: build docs
on:
  push:
    branches: [main]
jobs:
  build:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v3
      - name: set up python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.x
      - name: build
        run: python3 docsgen.py
      - name: commit changes # copied from ad-m/github-push-action
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "built docs" -a
      - name: push built files
        uses: ad-m/github-push-action@40bf560936a8022e68a3c00e7d2abefaf01305a6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}